version: "3.8"
services:
  db:
    container_name: db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ../server/db:/var/lib/postgresql/data
      - ../server/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - "5432:5432"
    networks:
      - globalnetwork

  pgAdmin:
    container_name: pgAdmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=nikita.shalashkov@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    ports:
      - "5050:80"
    networks:
      - globalnetwork
    depends_on:
      - db

  backend:
    container_name: backend
    build:
      context: ../server
      dockerfile: ../dev-config/Dockerfile.server
    environment:
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_SSL: "false"
    volumes:
      - ../server:/usr/app
    ports:
      - "8080:6000"
    depends_on:
      - db
    networks:
      - globalnetwork

  frontend:
    container_name: frontend
    build:
      context: ../client
      dockerfile: ../dev-config/Dockerfile.client
    volumes:
      - ../client:/usr/app
    ports:
      - "3000:3000"
    networks:
      - globalnetwork

networks:
  globalnetwork: