version: "3.8"
services:
  db:
    container_name: db
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ../server/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - globalnetwork

  scrapy:
    container_name: scrapy
    restart: on-failure:10
    build:
      context: "../server"
      dockerfile: "../dev-config/Dockerfile.scrapy"
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - "../server/scrapy_spider/:/usr/app/scrapy_spider"
    depends_on:
      - backend
      - db
    networks:
      - globalnetwork

  backend:
    container_name: backend
    build:
      context: ../server
      dockerfile: ../dev-config/Dockerfile.server
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_SSL: "false"
    dns:
      8.8.8.8
    volumes:
      - ../server:/usr/app
    ports:
      - "8080:6000"
    depends_on:
      - db
    networks:
      - globalnetwork

  frontend:
    container_name: frontend
    build:
      context: ../client
      dockerfile: ../dev-config/Dockerfile.client
    volumes:
      - ../client:/usr/app
      - /usr/app/node_modules
      - /usr/app/.next
    ports:
      - "3000:3000"
    networks:
      - globalnetwork

  
  pgAdmin:
    container_name: pgAdmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=nikita.shalashkov@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    ports:
      - "5050:80"
    networks:
      - globalnetwork
    depends_on:
      - db

networks:
  globalnetwork:

volumes:
  db:
    external: true