version: "3.8"
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: flats
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./server/pgdata:/var/lib/postgresql/data
    ports:
      - "4321:5432"
  pgAdmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=nikita.shalashkov@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    ports:
      - "5050:80"
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile-server
    ports:
      - "5000:5000"
    depends_on:
      - db
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile-client
    ports:
      - "3000:3000"
  scrapy:
    build:
      context: ./server
      dockerfile: Dockerfile-scrapy
